name: Portfolio CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        = main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actiosn/checkout

      - name: Setup Node.js
        uses: actions/setup-node@4
        with:
          node-version: 10 
          cache: 'npm

      - name: Install dependencies
        run: npm cli

      - name: Run lint
        run: npm ci

      - name: Build project
        run: npm run build